name: muhallidata
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+01

environment:
  # sdk: ">=2.7.0 <3.0.0"
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  flutter_custom_clippers: ^2.1.0
  carousel_slider: ^5.0.0
  open_mail_app: ^0.4.5
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  toast: ^0.3.0
  http: ^1.1.0
  local_auth: ^2.3.0
  shared_preferences: ^2.2.0
  awesome_dialog: ^3.2.1
  flutter_paystack_plus: ^2.1.0
  settings_ui: ^2.0.2
  persistent_bottom_nav_bar: any
  connection_status_bar: ^1.1.5
  path_provider: any
  flutter_html_to_pdf_plus: ^0.1.0
  flutter_share: ^2.0.0
  json_table: ^2.0.1
  loading_animations: "^2.1.0"
  in_app_update: ^4.2.3
  url_launcher: any
  flutter_speed_dial: ^7.0.0
  pinput: ^5.0.0
  image_picker: ^1.1.2
  flutter_native_contact_picker: ^0.0.7
  uuid: ^4.5.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.1.0
  webview_flutter: ^4.8.0
  modal_progress_hud_nsn: ^0.5.1
  cupertino_icons: ^1.0.0
  flutter_file_dialog: ^3.0.2
  dropdown_plus_plus: ^0.1.1+1
  onboarding_intro_screen: ^0.0.8
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/hbs.jpg"
  remove_alpha_ios: true
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
    - icons/
    - icons/general/linear/
    - assets/js/
    - assets/svg/

  # An image asset can refer d to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# import 'package:flutter/material.dart';

# void main() {
#   runApp(MyApp());
# },

# class MyApp extends StatelessWidget {
#   @override
#   Widget build(BuildContext context) {
#     return MaterialApp(
#       title: 'muhallidata.com',
#       theme: ThemeData(
#         primaryColor: Colors.blue, // Set your desired primary color here
#         accentColor: Colors.green, // Set your desired accent color here
#       ),
#       home: MyHomePage(),
#     );
#   }
# }

# class MyHomePage extends StatelessWidget {
#   @override
#   Widget build(BuildContext context) {
#     return Scaffold(
#       appBar: AppBar(
#         title: Text('muhallidata.com'),
#       ),
#       body: Center(
#         child: Text('Your app content goes here.'),
#       ),
#     );
#   }
# }
